server:
  port: 8083

spring:
  application:
    name: registration-service
  datasource:
    url: jdbc:mysql://localhost:3306/registration_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true